// Czech URL aliases mapping: czech path -> english path
// Users can access tools via Czech URLs which redirect to the canonical English URLs

export const categoryAliases: Record<string, string> = {
  obrazky: 'image-generic',
  png: 'png',
  pdf: 'pdf',
  text: 'string',
  video: 'video',
  cas: 'time',
  zvuk: 'audio',
  json: 'json',
  seznam: 'list',
  csv: 'csv',
  cisla: 'number',
  xml: 'xml',
  gif: 'gif',
  prevodniky: 'converters'
};

export const toolAliases: Record<string, string> = {
  // Number tools
  'cisla/soucet': 'number/sum',
  'cisla/generovat': 'number/generate',
  'cisla/aritmeticka-posloupnost': 'number/arithmetic-sequence',
  'cisla/nahodna-cisla': 'number/random-number-generator',
  'cisla/nahodne-porty': 'number/random-port-generator',
  'cisla/prevodnik-bajtu': 'number/byte-converter',
  'cisla/kalkulacka-dph': 'number/vat-calculator',
  'cisla/prevodnik-jednotek': 'number/unit-converter',
  'cisla/bmi-kalkulacka': 'number/bmi-calculator',
  'cisla/cena-jizdy': 'number/fuel-cost-calculator',
  'cisla/prevodnik-men': 'number/currency-converter',
  'cisla/qr-platba': 'number/qr-payment',
  'cisla/ohmov-zakon': 'number/ohms-law',
  'cisla/povrch-koule': 'number/sphere-area',
  'cisla/objem-koule': 'number/sphere-volume',
  'cisla/napeti-slackline': 'number/slackline',
  'cisla/ubytek-napeti': 'number/voltage-drop-in-wire',

  // String/Text tools
  'text/rozdelit': 'string/split',
  'text/spojit': 'string/join',
  'text/odstranit-duplikaty': 'string/remove-duplicate-lines',
  'text/morseovka': 'string/to-morse',
  'text/nahradit': 'string/text-replacer',
  'text/opakovat': 'string/repeat',
  'text/zkratit': 'string/truncate',
  'text/obratit': 'string/reverse',
  'text/nahodna-velikost': 'string/randomize-case',
  'text/velka-pismena': 'string/uppercase',
  'text/mala-pismena': 'string/lowercase',
  'text/velke-pocatecni': 'string/title-case',
  'text/extrahovat-podretezec': 'string/extract-substring',
  'text/vytvorit-palindrom': 'string/create-palindrome',
  'text/palindrom': 'string/palindrome',
  'text/uvozovky': 'string/quote',
  'text/rotovat': 'string/rotate',
  'text/rot13': 'string/rot13',
  'text/base64': 'string/base64',
  'text/statistiky': 'string/statistic',
  'text/cenzura': 'string/censor',
  'text/generator-hesel': 'string/password-generator',
  'text/url-kodovani': 'string/url-encode',
  'text/url-dekodovani': 'string/url-decode',
  'text/unicode': 'string/unicode',
  'text/skryte-znaky': 'string/hidden-character-detector',
  'text/odstranit-diakritiku': 'string/remove-diacritics',
  'text/lorem-ipsum': 'string/lorem-ipsum',
  'text/pocitadlo-slov': 'string/word-counter',
  'text/markdown-na-html': 'string/markdown-to-html',
  'text/porovnani-textu': 'string/text-diff',
  'text/generator-hashu': 'string/hash-generator',
  'text/generator-uuid': 'string/uuid-generator',
  'text/html-entity': 'string/html-entity',
  'text/jwt-dekoder': 'string/jwt-decoder',
  'text/prevodnik-barev': 'string/color-converter',
  'text/minifikace-css-js': 'string/css-js-minify',
  'text/regex-tester': 'string/regex-tester',

  // Image tools
  'obrazky/editor': 'image-generic/editor',
  'obrazky/zmena-velikosti': 'image-generic/resize',
  'obrazky/komprese': 'image-generic/compress',
  'obrazky/odstranit-pozadi': 'image-generic/remove-background',
  'obrazky/orez': 'image-generic/crop',
  'obrazky/orez-jpg': 'image-generic/crop-jpg',
  'obrazky/orez-webp': 'image-generic/crop-webp',
  'obrazky/pruhlednost': 'image-generic/change-opacity',
  'obrazky/zmena-barev': 'image-generic/change-colors',
  'obrazky/pruhledny-png': 'image-generic/create-transparent',
  'obrazky/text-z-obrazku': 'image-generic/image-to-text',
  'obrazky/qr-kod': 'image-generic/qr-code',
  'obrazky/otocit': 'image-generic/rotate',
  'obrazky/prevod-na-jpg': 'image-generic/convert-to-jpg',
  'obrazky/prevratit': 'image-generic/flip',
  'obrazky/vyber-barvy': 'image-generic/color-picker',

  // PNG tools
  'png/komprese-png': 'png/compress-png',
  'png/jpg-na-png': 'png/convert-jgp-to-png',
  'png/orez-png': 'png/crop-png',

  // PDF tools
  'pdf/rozdelit': 'pdf/split-pdf',
  'pdf/otocit': 'pdf/rotate-pdf',
  'pdf/komprimovat': 'pdf/compress-pdf',
  'pdf/ochranit': 'pdf/protect-pdf',
  'pdf/sloucit': 'pdf/merge-pdf',
  'pdf/do-epub': 'pdf/pdf-to-epub',
  'pdf/na-png': 'pdf/pdf-to-png',
  'pdf/obrazky-do-pdf': 'pdf/convert-to-pdf',
  'pdf/editor': 'pdf/editor',
  'pdf/word-do-pdf': 'pdf/word-to-pdf',
  'pdf/excel-do-pdf': 'pdf/excel-to-pdf',
  'pdf/pdf-do-word': 'pdf/pdf-to-word',
  'pdf/pdf-do-excel': 'pdf/pdf-to-excel',
  'pdf/word-do-html': 'pdf/word-to-html',
  'pdf/pdf-do-textu': 'pdf/pdf-to-text',
  'pdf/statistiky-docx': 'pdf/docx-stats',
  'pdf/sloucit-word': 'pdf/merge-word',
  'pdf/sloucit-excel': 'pdf/merge-excel',

  // JSON tools
  'json/formatovat': 'json/prettify',
  'json/minifikovat': 'json/minify',
  'json/stringify': 'json/stringify',
  'json/validovat': 'json/validateJson',
  'json/na-xml': 'json/json-to-xml',
  'json/na-csv': 'json/json-to-csv',
  'json/escapovat': 'json/escape-json',
  'json/porovnat': 'json/json-comparison',
  'json/na-yaml': 'json/json-to-yaml',
  'json/yaml-na-json': 'json/yaml-to-json',
  'json/excel-na-json': 'json/excel-to-json',

  // List tools
  'seznam/seradit': 'list/sort',
  'seznam/obratit': 'list/reverse',
  'seznam/zamihat': 'list/shuffle',
  'seznam/duplikovat': 'list/duplicate',
  'seznam/najit-unikatni': 'list/find-unique',
  'seznam/nejpopularnejsi': 'list/find-most-popular',
  'seznam/rotovat': 'list/rotate',
  'seznam/zkratit': 'list/truncate',
  'seznam/zabalit': 'list/wrap',
  'seznam/rozbalit': 'list/unwrap',
  'seznam/bloky': 'list/chunk',
  'seznam/seskupit': 'list/group',

  // CSV tools
  'csv/na-json': 'csv/csv-to-json',
  'csv/na-xml': 'csv/csv-to-xml',
  'csv/na-tsv': 'csv/csv-to-tsv',
  'csv/na-yaml': 'csv/csv-to-yaml',
  'csv/radky-na-sloupce': 'csv/csv-rows-to-columns',
  'csv/zmena-oddelovace': 'csv/change-csv-separator',
  'csv/neuplne-zaznamy': 'csv/find-incomplete-csv-records',
  'csv/transponovat': 'csv/transpose-csv',
  'csv/vlozit-sloupce': 'csv/insert-csv-columns',
  'csv/prohodit-sloupce': 'csv/swap-csv-columns',
  'csv/tsv-na-json': 'csv/tsv-to-json',
  'csv/csv-do-excel': 'csv/csv-to-excel',
  'csv/excel-do-csv': 'csv/excel-to-csv',

  // Time tools
  'cas/prestupny-rok': 'time/check-leap-years',
  'cas/dny-na-hodiny': 'time/convert-days-to-hours',
  'cas/hodiny-na-dny': 'time/convert-hours-to-days',
  'cas/sekundy-na-cas': 'time/convert-seconds-to-time',
  'cas/cas-na-sekundy': 'time/convert-time-to-seconds',
  'cas/unix-na-datum': 'time/convert-unix-to-date',
  'cas/crontab': 'time/crontab-guru',
  'cas/cas-mezi-daty': 'time/time-between-dates',
  'cas/zkratit-cas': 'time/truncate-clock-time',
  'cas/cas-na-desetinny': 'time/convert-time-to-decimal',
  'cas/discord-casove-razitko': 'time/discord-timestamp',

  // Video tools
  'video/rychlost': 'video/change-speed',
  'video/komprese': 'video/compress',
  'video/orez-videa': 'video/crop-video',
  'video/prevratit': 'video/flip',
  'video/smycka': 'video/loop',
  'video/sloucit': 'video/merge-video',
  'video/otocit': 'video/rotate',
  'video/orez': 'video/trim',
  'video/na-gif': 'video/video-to-gif',

  // Audio tools
  'zvuk/rychlost': 'audio/change-speed',
  'zvuk/extrahovat': 'audio/extract-audio',
  'zvuk/sloucit': 'audio/merge-audio',
  'zvuk/orez': 'audio/trim',

  // XML tools
  'xml/formatovat': 'xml/xml-beautifier',
  'xml/validovat': 'xml/xml-validator'
};
